<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <PlatformTarget>x86</PlatformTarget>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>Spotnet.Enc</AssemblyName>
    <RootNamespace>SpotnetEnc</RootNamespace>
  </PropertyGroup>
</Project>
