[CmdletBinding()]
param(
    [string]$CompilerPath,
    [switch]$BootstrapCompiler,
    [switch]$SkipBuild
)
$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest
$repoRoot = $PSScriptRoot
$artifactRoot = Join-Path $repoRoot 'artifacts\installer'
$toolRoot = Join-Path $repoRoot 'artifacts\installer-tools'
New-Item -ItemType Directory -Force -Path $artifactRoot, $toolRoot | Out-Null

function Get-SignedDownload([string]$Uri, [string]$Path, [string]$Publisher) {
    if (-not (Test-Path -LiteralPath $Path)) {
        Write-Host "Downloading $(Split-Path $Path -Leaf)..."
        Invoke-WebRequest -Uri $Uri -OutFile $Path -UseBasicParsing
    }
    $signature = Get-AuthenticodeSignature -LiteralPath $Path
    if ($signature.Status -ne 'Valid' -or $signature.SignerCertificate.Subject -notmatch $Publisher) {
        throw "Publisher signature validation failed for $Path. File will not be executed or packaged."
    }
}

if (-not $CompilerPath) {
    $candidates = @(
        (Join-Path $toolRoot 'InnoSetup7\ISCC.exe'),
        (Join-Path $env:ProgramFiles 'Inno Setup 7\ISCC.exe')
    )
    foreach ($candidate in $candidates) {
        if (Test-Path -LiteralPath $candidate) { $CompilerPath = $candidate; break }
    }
}
if (-not $CompilerPath -and $BootstrapCompiler) {
    $download = Join-Path $toolRoot 'innosetup-7.1.0-x64.exe'
    Get-SignedDownload 'https://github.com/jrsoftware/issrc/releases/download/is-7_1_0/innosetup-7.1.0-x64.exe' $download 'CN=Pyrsys B\.V\.'
    $compilerDirectory = Join-Path $toolRoot 'InnoSetup7'
    $process = Start-Process -FilePath $download -ArgumentList @('/PORTABLE=1', '/CURRENTUSER', '/VERYSILENT', '/SUPPRESSMSGBOXES', '/NORESTART', ('/DIR="' + $compilerDirectory + '"')) -WindowStyle Hidden -Wait -PassThru
    if ($process.ExitCode -ne 0) { throw "Inno Setup bootstrap failed: $($process.ExitCode)" }
    $CompilerPath = Join-Path $compilerDirectory 'ISCC.exe'
}
if (-not $CompilerPath -or -not (Test-Path -LiteralPath $CompilerPath)) {
    throw 'Install Inno Setup 7.1+, supply -CompilerPath, or use -BootstrapCompiler for a verified portable compiler under artifacts/.'
}

Push-Location $repoRoot
try {
    if (-not $SkipBuild) {
        & dotnet build reconstructed/Spotnet2/Spotnet.sln -c Release -v minimal
        if ($LASTEXITCODE -ne 0) { throw 'Application build failed.' }
        & dotnet test reconstructed/Spotnet2/Spotnet.Tests/Spotnet.Tests.csproj -c Release --no-build -v minimal
        if ($LASTEXITCODE -ne 0) { throw 'Tests failed; refusing to package.' }
    }
    & dotnet build tools/Spotnet.SetupHelper/Spotnet.SetupHelper.csproj -c Release -v minimal
    if ($LASTEXITCODE -ne 0) { throw 'Migration helper build failed.' }
    $appOutput = Join-Path $repoRoot 'reconstructed\Spotnet2\Spotnet\bin\Release\net472'
    $helperOutput = Join-Path $repoRoot 'tools\Spotnet.SetupHelper\bin\Release\net472'
    foreach ($binary in @('Spotnet.exe', 'Spotnet.Enc.dll', 'WebView2Loader.dll', 'x64\SQLite.Interop.dll', 'libvlc\win-x64\libvlc.dll')) {
        $binaryPath = Join-Path $appOutput $binary
        $bytes = [IO.File]::ReadAllBytes($binaryPath)
        $peOffset = [BitConverter]::ToInt32($bytes, 60)
        if ([BitConverter]::ToUInt16($bytes, $peOffset + 4) -ne 0x8664) { throw "Not an AMD64 binary: $binary" }
    }
    # A fresh staging directory prevents stale DLLs or personal runtime data entering the package.
    $payload = Join-Path $artifactRoot ('payload-' + [Guid]::NewGuid().ToString('N'))
    New-Item -ItemType Directory -Path $payload | Out-Null
    $trackedAssets = @(git ls-files -- reconstructed/Spotnet2/Spotnet/Data reconstructed/Spotnet2/Spotnet/Resources/ReleaseNotes)
    if ($LASTEXITCODE -ne 0) { throw 'Cannot enumerate tracked application assets.' }
    foreach ($file in Get-ChildItem -LiteralPath $appOutput -File) {
        if ($file.Extension -in @('.dll', '.exe') -or $file.Name -eq 'Spotnet.exe.config') {
            if ($file.Name -match '^(Awesomium|awesomium|Meta\.Vlc|Ionic\.Zip|Pri\.LongPath)' -or $file.Name -eq 'Squirrel.exe') { continue }
            Copy-Item -LiteralPath $file.FullName -Destination $payload
        }
    }
    foreach ($directory in @('x64', 'libvlc\win-x64')) {
        $target = Join-Path $payload (Split-Path $directory -Parent)
        New-Item -ItemType Directory -Force -Path $target | Out-Null
        Copy-Item -LiteralPath (Join-Path $appOutput $directory) -Destination $target -Recurse
    }
    foreach ($asset in $trackedAssets) {
        $relative = $asset.Substring('reconstructed/Spotnet2/Spotnet/'.Length)
        $destination = Join-Path $payload $relative
        New-Item -ItemType Directory -Force -Path (Split-Path $destination -Parent) | Out-Null
        Copy-Item -LiteralPath (Join-Path $repoRoot $asset) -Destination $destination
    }
    # Preserve satellite resource assemblies, if generated by the application build.
    foreach ($culture in @('nl', 'en', 'en-US')) {
        $cultureDir = Join-Path $appOutput $culture
        if (Test-Path -LiteralPath $cultureDir) { Copy-Item -LiteralPath $cultureDir -Destination $payload -Recurse }
    }
    $webview = Join-Path $toolRoot 'MicrosoftEdgeWebview2Setup.exe'
    Get-SignedDownload 'https://go.microsoft.com/fwlink/p/?LinkId=2124703' $webview 'O=Microsoft Corporation'
    & $CompilerPath /Q ('/DPayloadDir=' + $payload) ('/DHelperDir=' + $helperOutput) ('/DWebViewBootstrapper=' + $webview) ('/DOutputDir=' + $artifactRoot) installer/Spotnet3.iss
    if ($LASTEXITCODE -ne 0) { throw 'Installer compilation failed.' }
    $setupFile = Join-Path $artifactRoot 'Spotnet-3.0-x64-Setup.exe'
    $hash = (Get-FileHash -LiteralPath $setupFile -Algorithm SHA256).Hash
    "$hash  Spotnet-3.0-x64-Setup.exe" | Set-Content -LiteralPath ($setupFile + '.sha256') -Encoding ASCII
    Write-Host "Built: $setupFile"
    Write-Host "SHA256: $hash"
    Write-Warning 'The Spotnet installer is unsigned until a publisher signing certificate is supplied. No installer was run against your profile.'
}
finally { Pop-Location }
